name: firebase_livestream
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: 2.0.3

dependencies:
  flutter:
    sdk: flutter
  cornerstone: 2.0.0-nullsafety.7
  dartz: 0.10.0-nullsafety.1
  firebase_auth: 1.0.1
  firebase_core: 1.0.1
  flutter_bloc: 7.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: 8.0.0
  mocktail: 0.1.1

flutter:
  uses-material-design: true
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
