name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: subosito/flutter-action@v1.4.0
        - name: Install dependencies
          run: flutter pub get
        # - name: Generate files
        #   run: flutter pub run build_runner build --delete-conflicting-outputs
        - name: Format
          run: flutter format --set-exit-if-changed lib test
        - name: Analyze project source
          run: flutter analyze lib test
        - name: Test
          run: flutter test --coverage